using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using Csur.Datos;
using Csur.Negocio;
using DevExpress.XtraExport.Helpers;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Views.Grid;


namespace Csur.Presentacion.Admin
{
    public partial class FrmAdminPropietario : Csur.Presentacion.FrmMaestro
    {
        private DBcsurEntities dbContext = new DBcsurEntities();
        private EntidadFASE miEntidadFase = new EntidadFASE();
        private EntidadPERSONA miEntidadPersona = new EntidadPERSONA();
        private EntidadLOTE miEntidadLote = new EntidadLOTE();
        public FrmAdminPropietario()
        {
            InitializeComponent();

            this.InicializaDatosPersona();
            this.InicializaDatosLote();
            this.InicializaDatosPropietario();
        }

        private void InicializaDatosPersona()
        {
            dbContext.PERSONA.Load();
            var filtroPersona = dbContext.PERSONA.Local
                .Where(x => x.Tipo.Equals("socio"));
            pERSONABindingSource.DataSource = filtroPersona;
        }

        private void InicializaDatosLote()
        {
            dbContext.LOTE.Load();
            // This line of code is generated by Data Source Configuration Wizard
            lOTEBindingSource.DataSource = dbContext.LOTE.Local.ToBindingList();
        }

        private void InicializaDatosPropietario()
        {
            dbContext.PROPIETARIO.Load();
            pRopietarioBindingSource.DataSource = dbContext.PROPIETARIO.Local.ToBindingList();
            gridView1.OptionsBehavior.Editable = false;
            gridView1.OptionsSelection.EnableAppearanceFocusedCell = false;

        }

        private void listBoxControlPersona_SelectedIndexChanged(object sender, EventArgs e)
        {
            //Mensajes.MensajeRapido(listBoxControlPersona.SelectedIndex.ToString());
            miEntidadPersona = (EntidadPERSONA) listBoxControlPersona.SelectedItem;
            //gridView1.RefreshEditor(true);
            gridView1.Appearance.Reset();
            //Mensajes.MensajeRapido(miEntidadPersona.Nombre + " - " + miEntidadPersona.Apellido);
            //if(gridView1.Appearance.)
            //gridView1.SetAutoFilterValue(colIdLote,"2",AutoFilterCondition.BeginsWith);
            //gridView1.SetAutoFilterValue(colIdLote,);
            /*
            if (gridView1.Columns["colIdLote"] == 1)

            {

            }
            */
            /*
            for (int i = 0; i < gridView1.RowCount; i++)
            {
                gridView1.GetRow(i);
                gridControl1.MainView.Appearance.
            }
            */

        }

        private void gridView1_RowCellStyle(object sender, DevExpress.XtraGrid.Views.Grid.RowCellStyleEventArgs e)
        {

            /*
            GridView view = sender as GridView;
            //if (e.Column.FieldName == "colIdPersona")

            if (e.Column.FieldName == "IdPersona")
            {
                int valor = 0;
                try
                {
                    valor = Convert.ToInt32(view.GetRowCellValue(e.RowHandle, view.Columns["IdPersona"]).ToString());
                }
                catch (Exception exception)
                {
                    valor = 0;
                }
                
                if (valor == miEntidadPersona.IdPersona)
                {
                    Mensajes.MensajeRapido("Coincide");
                    e.Appearance.BackColor = Color.Aqua;
                    e.Appearance.BackColor2 = Color.LightCyan;
                }
                else
                {
                    e.Appearance.BackColor = Color.DarkSlateGray;
                    e.Appearance.BackColor2 = Color.Black;
                }

            }
            */
            
        }

        private void gridView1_RowStyle(object sender, RowStyleEventArgs e)
        {
            string valor = "";
            try
            {
                valor = miEntidadPersona.IdPersona.ToString();
            }
            catch (Exception exception)
            {
                valor = "";
            }

            GridView view = sender as GridView;
            if (e.RowHandle >= 0)
            {
                //int ver = 0;
                string miIdPersona = view.GetRowCellDisplayText(e.RowHandle, view.Columns["IdPersona"]);
                if (miIdPersona == valor)
                {
                    e.Appearance.BackColor = Color.Green;
                    e.Appearance.BackColor2 = Color.SeaShell;
                    e.HighPriority = true;
                    //view.MakeRowVisible(e.RowHandle, true);
                    //ver = RowVisibleState.Visible;
                    //view.IsRowVisible(e.RowHandle,RowVisibleState);

                }
                else
                {
                    //e.Appearance.BackColor = Color.DarkGray;
                    //e.Appearance.BackColor2 = Color.Black;
                    
                    //view.IsRowVisible(e.RowHandle, 0);
                    //view.MakeRowVisible(e.RowHandle, false);
                    //ver = RowVisibleState.Hidden;
                }

                
            }
        }
    }
}
