//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csur.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntidadVENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntidadVENTA()
        {
            this.PLANCUENTAS = new HashSet<EntidadPLANCUENTAS>();
            this.TRANSACCION = new HashSet<EntidadTRANSACCION>();
        }
    
        public int IdVenta { get; set; }
        public int IdLote { get; set; }
        public int IdCliente { get; set; }
        public int IdPersona { get; set; }
        public System.DateTime FechaContrato { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public string Observacion { get; set; }
        public string Tipo { get; set; }
    
        public virtual EntidadCLIENTE CLIENTE { get; set; }
        public virtual EntidadLOTE LOTE { get; set; }
        public virtual EntidadPERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadPLANCUENTAS> PLANCUENTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadTRANSACCION> TRANSACCION { get; set; }
    }
}
