//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csur.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntidadLOTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntidadLOTE()
        {
            this.VENTA = new HashSet<EntidadVENTA>();
            this.PROPIETARIO = new HashSet<EntidadPROPIETARIO>();
        }
    
        public int IdLote { get; set; }
        public string NombreLote { get; set; }
        public string Codigo { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public Nullable<int> Area { get; set; }
        public string Estado { get; set; }
        public int IdManzano { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual EntidadMANZANO MANZANO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadVENTA> VENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadPROPIETARIO> PROPIETARIO { get; set; }
    }
}
