//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csur.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntidadTRANSACCION
    {
        public int IdTransaacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Glosa { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public Nullable<int> IdPlanCuenta { get; set; }
        public Nullable<int> IdVenta { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string TipoTransaccion { get; set; }
        public string Observacion { get; set; }
        public int IdAsiento { get; set; }
    
        public virtual EntidadCLIENTE CLIENTE { get; set; }
        public virtual EntidadCUENTA CUENTA { get; set; }
        public virtual EntidadPERSONA PERSONA { get; set; }
        public virtual EntidadPLANCUENTAS PLANCUENTAS { get; set; }
        public virtual EntidadVENTA VENTA { get; set; }
        public virtual EntidadASIENTOS ASIENTOS { get; set; }
    }
}
