//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csur.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBcsurEntities : DbContext
    {
        public DBcsurEntities()
            : base("name=DBcsurEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EntidadCLIENTE> CLIENTE { get; set; }
        public virtual DbSet<EntidadCUENTA> CUENTA { get; set; }
        public virtual DbSet<EntidadFASE> FASE { get; set; }
        public virtual DbSet<EntidadLOTE> LOTE { get; set; }
        public virtual DbSet<EntidadMANZANO> MANZANO { get; set; }
        public virtual DbSet<EntidadPERSONA> PERSONA { get; set; }
        public virtual DbSet<EntidadPLANCUENTAS> PLANCUENTAS { get; set; }
        public virtual DbSet<EntidadTRANSACCION> TRANSACCION { get; set; }
        public virtual DbSet<EntidadVENTA> VENTA { get; set; }
        public virtual DbSet<EntidadPROPIETARIO> PROPIETARIO { get; set; }
        public virtual DbSet<EntidadCOMISION> COMISION { get; set; }
        public virtual DbSet<EntidadCONFIGURACION> CONFIGURACION { get; set; }
        public virtual DbSet<EntidadPARAMETROS> PARAMETROS { get; set; }
        public virtual DbSet<EntidadASIENTOS> ASIENTOS { get; set; }
    }
}
